<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class ListTopikSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');
        DB::table('listtopik')->insert([
            [
                'id_kejuruan' => 1,
                'title' => 'Pengenalan Pengembangan Full-stack',
                'description' => 'Pelajari dasar-dasar Pengembangan Full-stack, termasuk teknologi front-end dan back-end.',
                'status' => 'aktif',
                'price' => '500000',
                'level' => 'pemula',
                'duration' => '10 jam',
                'instructor' => 'John Doe',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 2,
                'title' => 'Jurnalisme Digital 101',
                'description' => 'Jelajahi dunia jurnalisme digital dan pelajari cara melaporkan berita di era digital.',
                'status' => 'aktif',
                'price' => '400000',
                'level' => 'menengah',
                'duration' => '8 jam',
                'instructor' => 'Jane Smith',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 3,
                'title' => 'Manajemen Produk ERP',
                'description' => 'Dapatkan wawasan tentang manajemen produk ERP, termasuk praktik terbaik dan alat-alatnya.',
                'status' => 'aktif',
                'price' => '600000',
                'level' => 'lanjutan',
                'duration' => '12 jam',
                'instructor' => 'Alice Johnson',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 2,
                'title' => 'Fotografi untuk Jurnalis',
                'description' => 'Kuasi seni fotojurnalistik dengan tips dan teknik praktis.',
                'status' => 'aktif',
                'price' => '450000',
                'level' => 'menengah',
                'duration' => '9 jam',
                'instructor' => 'Robert Brown',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 5,
                'title' => 'Analisis Data dengan Python',
                'description' => 'Pelajari cara menganalisis data menggunakan Python, termasuk pustaka seperti Pandas dan NumPy.',
                'status' => 'aktif',
                'price' => '550000',
                'level' => 'lanjutan',
                'duration' => '15 jam',
                'instructor' => 'Emily Davis',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 1,
                'title' => 'Dasar-dasar Desain UI/UX',
                'description' => 'Jelajahi prinsip-prinsip desain UI/UX, termasuk wireframing, prototyping, dan riset pengguna.',
                'status' => 'aktif',
                'price' => '480000',
                'level' => 'pemula',
                'duration' => '14 jam',
                'instructor' => 'Sophia Green',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 4,
                'title' => 'Strategi Pembuatan Konten',
                'description' => 'Pelajari strategi pembuatan konten yang efektif, termasuk perencanaan, produksi, dan distribusi konten.',
                'status' => 'aktif',
                'price' => '420000',
                'level' => 'menengah',
                'duration' => '7 jam',
                'instructor' => 'Michael White',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 4,
                'title' => 'Penulisan Naskah untuk Pembuat Konten',
                'description' => 'Kuasi seni penulisan naskah untuk video, podcast, dan konten media digital lainnya.',
                'status' => 'aktif',
                'price' => '450000',
                'level' => 'lanjutan',
                'duration' => '8 jam',
                'instructor' => 'Laura Blue',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 4,
                'title' => 'Esensial Komunikasi Merek',
                'description' => 'Pahami konsep inti komunikasi merek, termasuk pesan, nada bicara, dan keterlibatan audiens.',
                'status' => 'aktif',
                'price' => '0',
                'level' => 'menengah',
                'duration' => '10 jam',
                'instructor' => 'David Black',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 2,
                'title' => 'Teknik Investigasi Jurnalistik',
                'description' => 'Pelajari metode dan etika investigasi jurnalistik, dengan contoh praktis dan studi kasus.',
                'status' => 'aktif',
                'price' => '0',
                'level' => 'lanjutan',
                'duration' => '12 jam',
                'instructor' => 'Jane Smith',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 3,
                'title' => 'Manajemen Sistem ERP',
                'description' => 'Kuasi pengelolaan sistem ERP, dari implementasi hingga optimalisasi di perusahaan berskala besar.',
                'status' => 'aktif',
                'price' => '0',
                'level' => 'lanjutan',
                'duration' => '18 jam',
                'instructor' => 'Robert Brown',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 4,
                'title' => 'Fotojurnalisme Lanjutan',
                'description' => 'Kuasi seni bercerita melalui gambar yang kuat dalam berbagai konteks jurnalistik.',
                'status' => 'aktif',
                'price' => '0',
                'level' => 'lanjutan',
                'duration' => '15 jam',
                'instructor' => 'Emily Davis',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kejuruan' => 5,
                'title' => 'Analisis Data Besar dengan Python',
                'description' => 'Jelajahi teknik analisis data besar menggunakan Python, termasuk penambangan data, pembersihan, dan visualisasi.',
                'status' => 'aktif',
                'price' => '0',
                'level' => 'lanjutan',
                'duration' => '16 jam',
                'instructor' => 'Michael Taylor',
                'photo' => 'listtopic1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
